version: '3'
services:
  hbeat:
    image: python:3.10-alpine
    container_name: hbeat
    environment:
      - RABBITMQ_USER=user
      - RABBITMQ_PASS=password
    volumes:
      # ca_certificate.pem, client_certificate.pem, client_key.pem
      - ./certs:/etc/ssl/certs
      - ./publisher:/publisher
    command: >
      /bin/sh -c "
      pip install pika;
      sleep 60;
      while true; do
        python /publisher/hbeat.py;
        sleep 60;
      done"
